/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who am I? The React app calls this on load (it can't read the httpOnly cookie itself).
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Idempotent: always 204. Deletes the caller's own session (if any) and clears the cookie.
         *
         *     POST, not GET: SameSite=Lax still sends cookies on top-level GET navigations,
         *     so a GET logout could be triggered by any link or <img> on another site.
         */
        post: operations["logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Uploads
         * @description Newest first. Summary fields only (no bad-line samples).
         */
        get: operations["list_uploads_api_uploads_get"];
        put?: never;
        /** Create Upload */
        post: operations["create_upload_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload
         * @description One upload with status, progress and parse results. The status page polls this.
         */
        get: operations["get_upload_api_uploads__upload_id__get"];
        put?: never;
        post?: never;
        /** Delete Upload */
        delete: operations["delete_upload_api_uploads__upload_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{upload_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Dashboard data: stats, timeline and top-10 lists (one request for the whole page).
         */
        get: operations["get_summary_api_uploads__upload_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{upload_id}/events/histogram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events Histogram
         * @description Events over time for the current filters: the Logs chart above the table. The range is
         *     the time filter when set (so a zoom shows the whole zoomed window), else the matching events'.
         */
        get: operations["events_histogram_api_uploads__upload_id__events_histogram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{upload_id}/events/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count Events
         * @description How many events match the filters (for "Showing 51–75 of N" and page numbers). Separate from
         *     the page request so paging doesn't recount: the UI asks once per filter and caches it.
         */
        get: operations["count_events_api_uploads__upload_id__events_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{upload_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Log lines in time order, filtered (all filters AND-ed). Two ways to page:
         *     - `cursor` (KEYSET): `(ts, line_no) > cursor` uses the (ts, line_no) index, so Next/Previous
         *       are equally fast at any depth. `line_no` breaks ties between events with the same timestamp,
         *       so no row is skipped or repeated at a page boundary.
         *     - `offset`: jump straight to page N (clicking a page number). Postgres reads and discards the
         *       rows before it, which is fast for our files and slower only deep into multi-million-line ones.
         *     The total comes from /events/count (asked once per filter). The sort order is fixed.
         */
        get: operations["list_events_api_uploads__upload_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{upload_id}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Incidents
         * @description Incidents worst first, each with its findings. `min_priority=medium` hides the low ones.
         */
        get: operations["list_incidents_api_uploads__upload_id__incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review
         * @description The latest company-wide review (null if none was written yet).
         */
        get: operations["get_review_api_dashboard_review_get"];
        put?: never;
        /**
         * Create Review
         * @description Write a review of the company-wide picture now (Claude if configured, else the template).
         *     Plain `def`: the API call (~20 s) runs in the thread pool, not on the event loop.
         */
        post: operations["create_review_api_dashboard_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Investigations
         * @description All cases, unresolved first, then worst first. `q` searches the case number, user, name and entities;
         *     `detector` keeps cases with at least one finding of that kind (Detection Rules "View cases").
         */
        get: operations["list_investigations_api_investigations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investigations/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_api_investigations__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Investigation */
        patch: operations["update_investigation_api_investigations__case_id__patch"];
        trace?: never;
    };
    "/api/investigations/{case_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Note
         * @description Append-only: notes are never edited or deleted (add a new one to correct one).
         */
        post: operations["add_note_api_investigations__case_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rules */
        get: operations["get_rules_api_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Switch Detector
         * @description Switch a detector on or off for NEW scans (existing results are kept as they were scanned).
         */
        put: operations["switch_detector_api_rules__kind__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Everyone seen in the logs, riskiest first (users without an unresolved case after them).
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_users__username__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Review
         * @description The latest review of this user (null if none was written yet).
         */
        get: operations["get_user_review_api_users__username__review_get"];
        put?: never;
        /**
         * Create User Review
         * @description Write a review of this user's history now (Claude if configured, else the template). Only
         *     stand-ins reach the model: the overview below holds counts and dates, never names or IPs.
         */
        post: operations["create_user_review_api_users__username__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check for Docker Compose and Cloud Run. Needs no auth or DB.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Bucket Hours */
            bucket_hours: number;
            /** Points */
            points: components["schemas"]["app__api__users__ActivityPoint"][];
            /** Incidents */
            incidents: components["schemas"]["IncidentWindow"][];
        };
        /**
         * AiAssessment
         * @description The AI's triage suggestion: the analyst decides; words, never a percentage.
         */
        AiAssessment: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "likely_malicious" | "likely_benign" | "needs_more_evidence";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Reason */
            reason: string;
        };
        /** AnomalyOut */
        AnomalyOut: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Kind */
            kind: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Score */
            score: number;
            /** Reason */
            reason: string;
            /** Count */
            count: number;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /** BadLineOut */
        BadLineOut: {
            /** Line No */
            line_no: number;
            /** Reason */
            reason: string;
            /** Raw */
            raw: string;
        };
        /** Baseline */
        Baseline: {
            /** Active Days */
            active_days: number;
            /** Median Daily Events */
            median_daily_events: number;
            /** Median Daily Bytes Out */
            median_daily_bytes_out: number;
            /** Max Daily Bytes Out */
            max_daily_bytes_out: number;
            /** Hours Utc */
            hours_utc: number[];
            /** Blocked Share */
            blocked_share: number;
            /** Top Domains */
            top_domains: components["schemas"]["Count"][];
            /** Top Categories */
            top_categories: components["schemas"]["Count"][];
        };
        /** Body_create_upload_api_uploads_post */
        Body_create_upload_api_uploads_post: {
            /** File */
            file: string;
            /**
             * Log Timezone
             * @default UTC
             */
            log_timezone: string;
            /**
             * Format
             * @default auto
             * @enum {string}
             */
            format: "auto" | "csv" | "json";
        };
        /** CaseActivity */
        CaseActivity: {
            /** Bucket Minutes */
            bucket_minutes: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Points */
            points: components["schemas"]["app__api__investigations__ActivityPoint"][];
        };
        /**
         * CaseSearch
         * @description A ready-made Logs search. Filters come from our menu, never from the model.
         */
        CaseSearch: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Username */
            username: string | null;
            /** Host */
            host: string | null;
            /** Action */
            action: string | null;
            /** Anomalous */
            anomalous: boolean;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
        };
        /**
         * CaseUpdate
         * @description Only the fields sent are changed; send `"owner": null` / `"verdict": null` to clear them.
         */
        CaseUpdate: {
            /** Status */
            status?: ("open" | "investigating" | "resolved") | null;
            /** Owner */
            owner?: string | null;
            /** Verdict */
            verdict?: ("true_positive" | "false_positive" | "benign") | null;
            /**
             * Expected Updated At
             * Format: date-time
             */
            expected_updated_at: string;
        };
        /** CategoryCount */
        CategoryCount: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Incidents */
            incidents: number;
        };
        /** CategoryWeight */
        CategoryWeight: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Weight */
            weight: number;
        };
        /** Count */
        Count: {
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /** Cutoff */
        Cutoff: {
            /** Priority */
            priority: string;
            /** Min Score */
            min_score: number;
        };
        /** Dashboard */
        Dashboard: {
            kpis: components["schemas"]["Kpis"];
            /** Datasets */
            datasets: components["schemas"]["DatasetCount"][];
            /** Users At Risk */
            users_at_risk: components["schemas"]["RiskyUser"][];
            /** Severity */
            severity: {
                [key: string]: number;
            };
            /** Categories */
            categories: components["schemas"]["CategoryCount"][];
            /** Top Incidents */
            top_incidents: components["schemas"]["DashboardIncident"][];
            /** Top Entities */
            top_entities: components["schemas"]["Entity"][];
            /** Timeline */
            timeline: components["schemas"]["DayCount"][];
        };
        /** DashboardIncident */
        DashboardIncident: {
            /** Id */
            id: number;
            /** Case Id */
            case_id: number | null;
            /** Upload Id */
            upload_id: number;
            /** Username */
            username: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "high" | "medium" | "low";
            /** Priority Score */
            priority_score: number;
            /** Title */
            title: string;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /** Findings */
            findings: number;
        };
        /** DatasetCount */
        DatasetCount: {
            /** Upload Id */
            upload_id: number;
            /** Filename */
            filename: string;
            /** First Event */
            first_event: string | null;
            /** Last Event */
            last_event: string | null;
            /** Events */
            events: number;
            /** Flagged */
            flagged: number;
            /** Blocked */
            blocked: number;
        };
        /** DayCount */
        DayCount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Critical */
            critical: number;
            /** High */
            high: number;
            /** Medium */
            medium: number;
            /** Low */
            low: number;
        };
        /** DayIncidents */
        DayIncidents: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Incidents */
            incidents: number;
            /**
             * Worst
             * @enum {string}
             */
            worst: "critical" | "high" | "medium" | "low";
        };
        /** DetailEntity */
        DetailEntity: {
            /**
             * Type
             * @enum {string}
             */
            type: "user" | "device" | "ip" | "domain";
            /** Name */
            name: string;
            /** Detail */
            detail: string;
        };
        /** DetectorOut */
        DetectorOut: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /**
             * Layer
             * @enum {string}
             */
            layer: "rule" | "stat" | "ml" | "ai";
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /** Weight */
            weight: number;
            /** Summary */
            summary: string;
            /** Logic */
            logic: string[];
            /** False Positives */
            false_positives: string[];
            /** Tuning */
            tuning: string;
            /** Techniques */
            techniques: components["schemas"]["TechniqueOut"][];
            /** Enabled */
            enabled: boolean;
            /** Changed By */
            changed_by: string | null;
            /** Changed At */
            changed_at: string | null;
            /** Hits */
            hits: number;
            /** Cases */
            cases: number;
            /** Last Seen */
            last_seen: string | null;
        };
        /** DetectorSwitch */
        DetectorSwitch: {
            /** Enabled */
            enabled: boolean;
        };
        /** Device */
        Device: {
            /** Name */
            name: string;
            /** Os */
            os: string | null;
            /** Events */
            events: number;
        };
        /**
         * Entity
         * @description Something worth watching: a user, a device's source IP, or a destination domain.
         */
        Entity: {
            /**
             * Type
             * @enum {string}
             */
            type: "user" | "ip" | "domain";
            /** Name */
            name: string;
            /** Risk */
            risk: number;
            /** Alerts */
            alerts: number;
            /** Detail */
            detail: string;
        };
        /** EntityChip */
        EntityChip: {
            /**
             * Type
             * @enum {string}
             */
            type: "user" | "device" | "ip" | "domain";
            /** Name */
            name: string;
        };
        /** EventCount */
        EventCount: {
            /** Total */
            total: number;
            /** By Severity */
            by_severity: {
                [key: string]: number;
            };
        };
        /** EventHistogram */
        EventHistogram: {
            /** Bucket Minutes */
            bucket_minutes: number;
            /** Points */
            points: components["schemas"]["HistogramPoint"][];
        };
        /** EventOut */
        EventOut: {
            /** Line No */
            line_no: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Username */
            username: string;
            /** Client Ip */
            client_ip: string;
            /** Method */
            method: string | null;
            /** Url */
            url: string;
            /** Host */
            host: string | null;
            /** Action */
            action: string;
            /** Category */
            category: string | null;
            /** Risk Score */
            risk_score: number;
            /** Status Code */
            status_code: number | null;
            /** Bytes Out */
            bytes_out: number;
            /** Bytes In */
            bytes_in: number;
            /** Threat */
            threat: string | null;
            /** User Agent */
            user_agent: string | null;
            /** File Type */
            file_type: string | null;
            /** Device */
            device: string | null;
            /** Device Os */
            device_os: string | null;
            /** Rule Hits */
            rule_hits: string[];
            /** Rule Max Score */
            rule_max_score: number;
            /**
             * Windows
             * @default []
             */
            windows: string[];
        };
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** EvidenceItem */
        EvidenceItem: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /** Score */
            score: number;
            /**
             * Level
             * @enum {string}
             */
            level: "critical" | "high" | "medium" | "low";
            /**
             * Source
             * @enum {string}
             */
            source: "rule" | "stat" | "ml" | "ai";
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramPoint */
        HistogramPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Total */
            total: number;
            /** Blocked */
            blocked: number;
            /** Flagged */
            flagged: number;
        };
        /** IncidentList */
        IncidentList: {
            /** Upload Id */
            upload_id: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Incidents */
            incidents: components["schemas"]["IncidentOut"][];
        };
        /** IncidentOut */
        IncidentOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /** Title */
            title: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "high" | "medium" | "low";
            /** Priority Score */
            priority_score: number;
            /** Categories */
            categories: string[];
            /** Narrative */
            narrative: string | null;
            /** Next Steps */
            next_steps: string[];
            /** Anomalies */
            anomalies: components["schemas"]["AnomalyOut"][];
        };
        /** IncidentWindow */
        IncidentWindow: {
            /** Case Id */
            case_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "high" | "medium" | "low";
        };
        /** InvestigationDetail */
        InvestigationDetail: {
            /** Id */
            id: number;
            /** Number */
            number: string;
            /** Name */
            name: string;
            /** Title */
            title: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "high" | "medium" | "low";
            /** Risk */
            risk: number;
            /** Signals */
            signals: number;
            /** Alerts */
            alerts: number;
            /** Entities */
            entities: components["schemas"]["EntityChip"][];
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "investigating" | "resolved";
            /** Owner */
            owner: string | null;
            /** Verdict */
            verdict: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /** Upload Id */
            upload_id: number;
            /** Why Flagged */
            why_flagged: string | null;
            /** Narrative Source */
            narrative_source: ("ai" | "template") | null;
            /** Next Steps */
            next_steps: string[];
            /** Next Questions */
            next_questions: string[];
            ai_assessment: components["schemas"]["AiAssessment"] | null;
            /** Searches */
            searches: components["schemas"]["CaseSearch"][];
            /** Risk Breakdown */
            risk_breakdown: components["schemas"]["RiskPart"][];
            /** Detection Signals */
            detection_signals: components["schemas"]["Signal"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceItem"][];
            /** Related Entities */
            related_entities: components["schemas"]["DetailEntity"][];
            /** Notes */
            notes: components["schemas"]["NoteOut"][];
            /** Analysts */
            analysts: string[];
            activity: components["schemas"]["CaseActivity"];
        };
        /** InvestigationItem */
        InvestigationItem: {
            /** Id */
            id: number;
            /** Number */
            number: string;
            /** Name */
            name: string;
            /** Title */
            title: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "high" | "medium" | "low";
            /** Risk */
            risk: number;
            /** Signals */
            signals: number;
            /** Alerts */
            alerts: number;
            /** Entities */
            entities: components["schemas"]["EntityChip"][];
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "investigating" | "resolved";
            /** Owner */
            owner: string | null;
            /** Verdict */
            verdict: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /** Upload Id */
            upload_id: number;
        };
        /** KeyFinding */
        KeyFinding: {
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "high" | "medium" | "low";
            /** Text */
            text: string;
        };
        /** Kpis */
        Kpis: {
            /** Incidents */
            incidents: number;
            /** Critical */
            critical: number;
            /** Affected Users */
            affected_users: number;
            /** Flagged Events */
            flagged_events: number;
            /** Blocked Events */
            blocked_events: number;
            /** Events */
            events: number;
            /** Datasets */
            datasets: number;
            /** Uploads */
            uploads: number;
            /** Findings */
            findings: number;
            /** Findings High */
            findings_high: number;
            /** Open Cases */
            open_cases: number;
            /** Unassigned Urgent */
            unassigned_urgent: number;
            /** High Risk Users */
            high_risk_users: number;
            /** High Risk Ips */
            high_risk_ips: number;
            /** Events Last Period */
            events_last_period: number;
            /** Events Previous Period */
            events_previous_period: number | null;
            /** Period Days */
            period_days: number;
        };
        /** NarrativeOut */
        NarrativeOut: {
            /**
             * Source
             * @enum {string}
             */
            source: "ai" | "template";
            /** Model */
            model: string | null;
            /** Summary */
            summary: string;
            /** Generated At */
            generated_at: string;
        };
        /** NoteIn */
        NoteIn: {
            /** Text */
            text: string;
        };
        /** NoteOut */
        NoteOut: {
            /** Id */
            id: number;
            /** Author */
            author: string | null;
            /** Text */
            text: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReviewOut */
        ReviewOut: {
            /** Id */
            id: number;
            /**
             * Source
             * @enum {string}
             */
            source: "ai" | "template";
            /** Model */
            model: string | null;
            /** Headline */
            headline: string | null;
            /** Key Findings */
            key_findings: components["schemas"]["KeyFinding"][];
            /** Actions */
            actions: string[];
            /** Summary */
            summary: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /** Incident Count */
            incident_count: number;
            /** Stale */
            stale: boolean;
        };
        /** RiskPart */
        RiskPart: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Weight */
            weight: number;
            /** Counted */
            counted: boolean;
        };
        /** RiskyUser */
        RiskyUser: {
            /** Username */
            username: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "critical" | "high" | "medium" | "low";
            /** Priority Score */
            priority_score: number;
            /** Incidents */
            incidents: number;
            /** Findings */
            findings: number;
            /** Reason */
            reason: string;
            /** Upload Id */
            upload_id: number;
        };
        /** RulesCatalog */
        RulesCatalog: {
            /** Detectors */
            detectors: components["schemas"]["DetectorOut"][];
            scoring: components["schemas"]["Scoring"];
            /** Tactics */
            tactics: string[];
            /** Blind Spots */
            blind_spots: string[];
        };
        /** Scoring */
        Scoring: {
            /** Weights */
            weights: components["schemas"]["CategoryWeight"][];
            /** Corroboration Bonus */
            corroboration_bonus: number;
            /** Corroboration Min */
            corroboration_min: number;
            /** Chain Hours */
            chain_hours: number;
            /** Cutoffs */
            cutoffs: components["schemas"]["Cutoff"][];
            /** Approved Hosts */
            approved_hosts: string[];
            /** Approved Weight */
            approved_weight: number;
        };
        /** Signal */
        Signal: {
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Counted */
            counted: boolean;
        };
        /** SummaryStats */
        SummaryStats: {
            /** Total Events */
            total_events: number;
            /** First Event */
            first_event: string | null;
            /** Last Event */
            last_event: string | null;
            /** Unique Users */
            unique_users: number;
            /** Unique Hosts */
            unique_hosts: number;
            /** Unique Client Ips */
            unique_client_ips: number;
            /** Allowed */
            allowed: number;
            /** Blocked */
            blocked: number;
            /** Bytes Out */
            bytes_out: number;
            /** Bytes In */
            bytes_in: number;
            /** Threat Events */
            threat_events: number;
            /** Flagged Events */
            flagged_events: number;
            /** Rule Hits */
            rule_hits: {
                [key: string]: number;
            };
        };
        /** TechniqueOut */
        TechniqueOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tactic */
            tactic: string;
            /** Url */
            url: string;
            /** Approximate */
            approximate: boolean;
            /** Supports */
            supports: boolean;
        };
        /** Timeline */
        Timeline: {
            /** Bucket */
            bucket: string;
            /** Points */
            points: components["schemas"]["TimelinePoint"][];
        };
        /** TimelinePoint */
        TimelinePoint: {
            /** T */
            t: string;
            /** Total */
            total: number;
            /** Blocked */
            blocked: number;
            /** Flagged */
            flagged: number;
        };
        /** TopItem */
        TopItem: {
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /** TopLists */
        TopLists: {
            /** Users By Requests */
            users_by_requests: components["schemas"]["TopItem"][];
            /** Users By Bytes Out */
            users_by_bytes_out: components["schemas"]["TopItem"][];
            /** Hosts */
            hosts: components["schemas"]["TopItem"][];
            /** Categories */
            categories: components["schemas"]["TopItem"][];
            /** Blocked Categories */
            blocked_categories: components["schemas"]["TopItem"][];
            /** Threats */
            threats: components["schemas"]["TopItem"][];
        };
        /** UploadCreated */
        UploadCreated: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Format */
            format: string;
            /** Log Timezone */
            log_timezone: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Uploaded By */
            uploaded_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Line Count */
            line_count: number | null;
            /** Bad Line Count */
            bad_line_count: number | null;
            /** Previous Uploads */
            previous_uploads: number;
        };
        /**
         * UploadDetail
         * @description UploadOut plus the larger fields, only for a single upload.
         */
        UploadDetail: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Format */
            format: string;
            /** Log Timezone */
            log_timezone: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Uploaded By */
            uploaded_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Line Count */
            line_count: number | null;
            /** Bad Line Count */
            bad_line_count: number | null;
            /** Bad Line Samples */
            bad_line_samples: components["schemas"]["BadLineOut"][];
            /** Completed At */
            completed_at: string | null;
            /** Disabled Detectors */
            disabled_detectors: string[];
        };
        /** UploadOut */
        UploadOut: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Format */
            format: string;
            /** Log Timezone */
            log_timezone: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Uploaded By */
            uploaded_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Line Count */
            line_count: number | null;
            /** Bad Line Count */
            bad_line_count: number | null;
        };
        /** UploadSummaryOut */
        UploadSummaryOut: {
            /** Upload Id */
            upload_id: number;
            stats: components["schemas"]["SummaryStats"];
            timeline: components["schemas"]["Timeline"];
            top: components["schemas"]["TopLists"];
            /** Computed At */
            computed_at: string;
            narrative: components["schemas"]["NarrativeOut"] | null;
        };
        /** UserListItem */
        UserListItem: {
            /** Username */
            username: string;
            /** Department */
            department: string | null;
            /** Risk */
            risk: number | null;
            /** Priority */
            priority: ("critical" | "high" | "medium" | "low") | null;
            /** Open Cases */
            open_cases: number;
            /** Cases */
            cases: number;
            /** Events */
            events: number;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Reason */
            reason: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Username */
            username: string;
        };
        /** UserProfile */
        UserProfile: {
            /** Username */
            username: string;
            /** Department */
            department: string | null;
            /** Location */
            location: string | null;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Events */
            events: number;
            /** Datasets */
            datasets: number;
            /** Devices */
            devices: components["schemas"]["Device"][];
            /** Ips */
            ips: components["schemas"]["Count"][];
            risk: components["schemas"]["UserRisk"];
            verdicts: components["schemas"]["Verdicts"];
            /** Cases */
            cases: components["schemas"]["InvestigationItem"][];
            /** Timeline */
            timeline: components["schemas"]["DayIncidents"][];
            baseline: components["schemas"]["Baseline"];
            activity: components["schemas"]["Activity"];
        };
        /** UserRisk */
        UserRisk: {
            /** Score */
            score: number | null;
            /** Priority */
            priority: ("critical" | "high" | "medium" | "low") | null;
            /** Case Id */
            case_id: number | null;
            /** Explanation */
            explanation: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Verdicts */
        Verdicts: {
            /** True Positive */
            true_positive: number;
            /** False Positive */
            false_positive: number;
            /** Benign */
            benign: number;
            /** Unresolved */
            unresolved: number;
        };
        /** ActivityPoint */
        app__api__investigations__ActivityPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Total */
            total: number;
            /** Blocked */
            blocked: number;
            /** Flagged */
            flagged: number;
        };
        /** ActivityPoint */
        app__api__users__ActivityPoint: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Events */
            events: number;
            /** Blocked */
            blocked: number;
            /** Flagged */
            flagged: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_login_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_uploads_api_uploads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_upload_api_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_upload_api_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_api_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_upload_api_uploads__upload_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_uploads__upload_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_histogram_api_uploads__upload_id__events_histogram_get: {
        parameters: {
            query?: {
                username?: string | null;
                action?: ("Allowed" | "Blocked") | null;
                category?: string | null;
                host?: string | null;
                flagged?: boolean;
                rule?: ("zscaler_threat" | "high_risk_allowed" | "scripted_client" | "executable_download") | null;
                in_window?: boolean;
                start?: string | null;
                end?: string | null;
                q?: string | null;
                min_score?: number | null;
                window_source?: ("stat" | "ml" | "ai") | null;
                anomalous?: boolean;
                severity?: ("critical" | "high" | "medium" | "low" | "none")[] | null;
                source?: ("rule:zscaler_threat" | "rule:high_risk_allowed" | "rule:scripted_client" | "rule:executable_download" | "window:stat" | "window:ml" | "window:ai")[] | null;
            };
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventHistogram"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_events_api_uploads__upload_id__events_count_get: {
        parameters: {
            query?: {
                username?: string | null;
                action?: ("Allowed" | "Blocked") | null;
                category?: string | null;
                host?: string | null;
                flagged?: boolean;
                rule?: ("zscaler_threat" | "high_risk_allowed" | "scripted_client" | "executable_download") | null;
                in_window?: boolean;
                start?: string | null;
                end?: string | null;
                q?: string | null;
                min_score?: number | null;
                window_source?: ("stat" | "ml" | "ai") | null;
                anomalous?: boolean;
                severity?: ("critical" | "high" | "medium" | "low" | "none")[] | null;
                source?: ("rule:zscaler_threat" | "rule:high_risk_allowed" | "rule:scripted_client" | "rule:executable_download" | "window:stat" | "window:ml" | "window:ai")[] | null;
            };
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventCount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_uploads__upload_id__events_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                offset?: number | null;
                limit?: number;
                username?: string | null;
                action?: ("Allowed" | "Blocked") | null;
                category?: string | null;
                host?: string | null;
                flagged?: boolean;
                rule?: ("zscaler_threat" | "high_risk_allowed" | "scripted_client" | "executable_download") | null;
                in_window?: boolean;
                start?: string | null;
                end?: string | null;
                q?: string | null;
                min_score?: number | null;
                window_source?: ("stat" | "ml" | "ai") | null;
                anomalous?: boolean;
                severity?: ("critical" | "high" | "medium" | "low" | "none")[] | null;
                source?: ("rule:zscaler_threat" | "rule:high_risk_allowed" | "rule:scripted_client" | "rule:executable_download" | "window:stat" | "window:ml" | "window:ai")[] | null;
            };
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_uploads__upload_id__incidents_get: {
        parameters: {
            query?: {
                min_priority?: "critical" | "high" | "medium" | "low";
            };
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_api_dashboard_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_review_api_dashboard_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_api_investigations_get: {
        parameters: {
            query?: {
                q?: string | null;
                severity?: ("critical" | "high" | "medium" | "low") | null;
                status?: ("open" | "investigating" | "resolved") | "unresolved" | null;
                detector?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_api_investigations__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investigation_api_investigations__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note_api_investigations__case_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rules_api_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesCatalog"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_detector_api_rules__kind__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetectorSwitch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_users__username__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_review_api_users__username__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_review_api_users__username__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
