"""add rule hits to events

Revision ID: 199089034cdc
Revises: 7d29a06d8ab9
Create Date: 2026-10-03 02:12:27.923864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '199089034cdc'
down_revision: Union[str, Sequence[str], None] = '7d29a06d8ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('rule_hits', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('events', sa.Column('rule_max_score', sa.REAL(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'rule_max_score')
    op.drop_column('events', 'rule_hits')
    # ### end Alembic commands ###
