"""create cases and case_notes

Revision ID: 52b22ef713e3
Revises: d19a7706a021
Create Date: 2026-10-04 10:58:17.765513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b22ef713e3'
down_revision: Union[str, Sequence[str], None] = 'd19a7706a021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1001), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'investigating', 'resolved')", name=op.f('ck_cases_status')),
    sa.CheckConstraint("verdict IN ('true_positive', 'false_positive', 'benign')", name=op.f('ck_cases_verdict')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_cases_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('username', 'start_ts', 'end_ts', 'title', name=op.f('uq_cases_username'))
    )
    op.create_table('case_notes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_case_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_notes_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_notes'))
    )
    op.create_index(op.f('ix_case_notes_case_id'), 'case_notes', ['case_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: one case per unique incident of the completed uploads analyzed so far, numbered
    # in time order (later analyses register their incidents in pass 2).
    op.execute("""
        INSERT INTO cases (username, start_ts, end_ts, title)
        SELECT username, start_ts, end_ts, title FROM (
            SELECT DISTINCT i.username, i.start_ts, i.end_ts, i.title
            FROM incidents i JOIN uploads u ON u.id = i.upload_id WHERE u.status = 'done'
        ) unique_incidents
        ORDER BY start_ts, username, title
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_notes_case_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_table('cases')
    # ### end Alembic commands ###
