"""create upload summary table

Revision ID: 5332343b7bac
Revises: 199089034cdc
Create Date: 2026-10-03 02:21:58.608282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5332343b7bac'
down_revision: Union[str, Sequence[str], None] = '199089034cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_summary',
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_n', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_upload_summary_upload_id_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upload_id', name=op.f('pk_upload_summary'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_summary')
    # ### end Alembic commands ###
