"""create events table

Revision ID: 7d29a06d8ab9
Revises: e190605a6ea7
Create Date: 2026-10-02 19:49:36.278869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d29a06d8ab9'
down_revision: Union[str, Sequence[str], None] = 'e190605a6ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('client_ip', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=False),
    sa.Column('bytes_out', sa.BigInteger(), nullable=False),
    sa.Column('bytes_in', sa.BigInteger(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('server_ip', sa.Text(), nullable=True),
    sa.Column('protocol', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('app_name', sa.Text(), nullable=True),
    sa.Column('threat', sa.Text(), nullable=True),
    sa.Column('malware_category', sa.Text(), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_events_upload_id_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upload_id', 'line_no', name=op.f('pk_events')),
    postgresql_partition_by='LIST (upload_id)'
    )
    op.create_index('ix_events_ts_line', 'events', ['ts', 'line_no'], unique=False)
    op.create_index('ix_events_username_ts', 'events', ['username', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_username_ts', table_name='events')
    op.drop_index('ix_events_ts_line', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
