"""add uploads retry_at

Revision ID: 7e9fe313003a
Revises: e7efcbe3e602
Create Date: 2026-10-03 15:20:06.397176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9fe313003a'
down_revision: Union[str, Sequence[str], None] = 'e7efcbe3e602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('retry_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'retry_at')
    # ### end Alembic commands ###
