"""create company_reviews table

Revision ID: d19a7706a021
Revises: 7e9fe313003a
Create Date: 2026-10-03 18:28:22.282930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19a7706a021'
down_revision: Union[str, Sequence[str], None] = '7e9fe313003a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_reviews',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("source IN ('ai', 'template')", name=op.f('ck_company_reviews_source')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_company_reviews_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_reviews'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_reviews')
    # ### end Alembic commands ###
