"""create uploads table

Revision ID: e190605a6ea7
Revises: d58cacf90a9e
Create Date: 2026-10-02 19:26:29.749419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e190605a6ea7'
down_revision: Union[str, Sequence[str], None] = 'd58cacf90a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('log_timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_key', sa.Text(), nullable=False),
    sa.Column('parquet_key', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('bad_line_count', sa.Integer(), nullable=True),
    sa.Column('bad_line_samples', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("format IN ('csv', 'json')", name=op.f('ck_uploads_format')),
    sa.CheckConstraint("status IN ('queued', 'processing', 'done', 'failed')", name=op.f('ck_uploads_status')),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_uploads_progress')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_uploads_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploads'))
    )
    op.create_index('ix_uploads_queued', 'uploads', ['created_at'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index(op.f('ix_uploads_uploaded_by'), 'uploads', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_uploaded_by'), table_name='uploads')
    op.drop_index('ix_uploads_queued', table_name='uploads', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('uploads')
    # ### end Alembic commands ###
