"""create incidents table

Revision ID: e7efcbe3e602
Revises: eacfebb1c3d8
Create Date: 2026-10-03 12:32:02.149667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7efcbe3e602'
down_revision: Union[str, Sequence[str], None] = 'eacfebb1c3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('priority_score', sa.REAL(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('critical', 'high', 'medium', 'low')", name=op.f('ck_incidents_priority')),
    sa.CheckConstraint('end_ts >= start_ts', name=op.f('ck_incidents_window')),
    sa.CheckConstraint('priority_score >= 0 AND priority_score <= 1', name=op.f('ck_incidents_priority_score')),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_incidents_upload_id_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index('ix_incidents_upload_priority', 'incidents', ['upload_id', sa.literal_column('priority_score DESC')], unique=False)
    op.add_column('anomalies', sa.Column('incident_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_anomalies_incident_id'), 'anomalies', ['incident_id'], unique=False)
    op.create_foreign_key(op.f('fk_anomalies_incident_id_incidents'), 'anomalies', 'incidents', ['incident_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_anomalies_incident_id_incidents'), 'anomalies', type_='foreignkey')
    op.drop_index(op.f('ix_anomalies_incident_id'), table_name='anomalies')
    op.drop_column('anomalies', 'incident_id')
    op.drop_index('ix_incidents_upload_priority', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
