"""create anomalies table

Revision ID: eacfebb1c3d8
Revises: 5332343b7bac
Create Date: 2026-10-03 11:03:22.802190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eacfebb1c3d8'
down_revision: Union[str, Sequence[str], None] = '5332343b7bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('score', sa.REAL(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("source IN ('rule', 'stat', 'ml')", name=op.f('ck_anomalies_source')),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_anomalies_score')),
    sa.CheckConstraint('window_end >= window_start', name=op.f('ck_anomalies_window')),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('fk_anomalies_upload_id_uploads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies'))
    )
    op.create_index('ix_anomalies_upload_user_start', 'anomalies', ['upload_id', 'username', 'window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anomalies_upload_user_start', table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
